# Generated by Django 5.0.6 on 2024-08-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGroupsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Groups_Name', models.TextField()),
                ('Person_Name', models.TextField()),
                ('Group_Host', models.TextField()),
                ('Total_No_Of_Person', models.TextField()),
                ('No_Of_Active_Members', models.TextField()),
                ('GroupStatus', models.TextField()),
            ],
        ),
    ]
