# Generated by Django 5.0.6 on 2024-08-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_testing', '0002_newgroupsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgroupsmodel',
            name='PersonStatus',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
