# Generated by Django 5.0.6 on 2024-08-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels_testing', '0003_newgroupsmodel_personstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newgroupsmodel',
            old_name='GroupStatus',
            new_name='Group_Status',
        ),
        migrations.RenameField(
            model_name='newgroupsmodel',
            old_name='PersonStatus',
            new_name='Person_Status',
        ),
    ]
