# Generated by Django 5.0.6 on 2024-08-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_testing', '0004_rename_groupstatus_newgroupsmodel_group_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgroupsmodel',
            name='Group_Admin',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
