# Generated by Django 5.0.6 on 2024-08-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels_testing', '0005_newgroupsmodel_group_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newgroupsmodel',
            name='Group_Admin',
        ),
    ]
