# Generated by Django 5.0.6 on 2024-08-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_testing', '0007_newgroupsmodel_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgroupsmodel',
            name='Host_Permissions',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newgroupsmodel',
            name='Login_Status',
            field=models.TextField(default=222),
            preserve_default=False,
        ),
    ]
