# Generated by Django 5.0.6 on 2024-08-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_testing', '0008_newgroupsmodel_host_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgroupsmodel',
            name='Channel_Layer',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
