# Generated by Django 5.0.6 on 2024-08-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels_testing', '0009_newgroupsmodel_channel_layer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newgroupsmodel',
            name='Channel_Layer',
        ),
        migrations.RemoveField(
            model_name='newgroupsmodel',
            name='Host_Permissions',
        ),
        migrations.RemoveField(
            model_name='newgroupsmodel',
            name='Login_Status',
        ),
    ]
