# Generated by Django 5.0.6 on 2024-08-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels_testing', '0011_chatmechatstoringmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatModel',
        ),
        migrations.DeleteModel(
            name='GroupsName',
        ),
    ]
